# It suit the follwoing ATTENTION models: 
#   - nystromformer 
#   - cosformer
ATTENTION: 'nystromformer'
eps: 1e-8
num_landmarks: 64
pinv_iterations: 64
NUM_CLASSES: 4
PATCH_SIZE: 16
DEPTH: 2
HEADS: 4
