# It suit the follwoing ATTENTION models: 
#   - nystromformer 
#   - cosformer
ATTENTION: 'cosformer'
eps: 1e-8
num_landmarks: 64
pinv_iterations: 64
NUM_CLASSES: 96
PATCH_SIZE: 16
DEPTH: 2
HEADS: 4
