EPOCHS: 1
SEED: 0
BATCH_SIZE: 4
DATA_THREADS: 5 # try different data thread
PRINT_BATCH: 50
LEARNING_RATE: 1e-5 # default: 0.0001
PRETRAINED_STATE_PATH: None # Missing value. Must be provided at command line
GPU: 0